# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Unit macOS

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-12
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        include:
          # - name: "clang17"
          #   compiler: "clang-17"
          #   build: unit
          #   build_type: RelWithDebInfo
          #   cxx_flags: "-stdlib=libc++" # For verbosity. This is already the default.

          - name: "gcc13"
            compiler: "gcc-13"
            build_type: RelWithDebInfo
            cxx_flags: "-std=c++23"

          - name: "gcc12"
            compiler: "gcc-12"
            build_type: RelWithDebInfo

          - name: "gcc11"
            compiler: "gcc-11"
            build_type: RelWithDebInfo

    steps:
      - name: Checkout SeqAn3
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 75M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.16.9

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake ../test/unit -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                             -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
                             -DSEQAN3_VERBOSE_TESTS=OFF
          make -j3 gtest_build

      - name: Build tests
        run: |
          ccache -z
          cd build
          make -k -j3
          ccache -sv

      - name: Run tests
        run: |
          cd build
          ctest . -j3 --output-on-failure
